[project]
name = "kafka-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka>=2.13.0",
    "faker>=40.5.1",
    "fastavro>=1.12.1",
    "psycopg2-binary>=2.9.11",
]
